name: Code Checks
on: [push]
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - name: Install dependecies
              run: yarn install
            - name: Check lint
              run: yarn lint
            - name: Check prettier
              run: yarn prettier-check
            - name: Run tests
              run: yarn test
